[package]
name = "charsetrs"
version = "0.1.0"
edition = "2021"

[lib]
name = "charsetrs"
crate-type = ["cdylib"]
path = "src/core/lib.rs"

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
encoding_rs = "0.8"
chardet = "0.2"
